document.write("document.write(\"<html>\");");
document.write("document.write(\"    <head>\");");
document.write("document.write(\"    <title>Your Title Here</title>\");");
document.write("document.write(\"    \");");
document.write("document.write(\"    \");");
document.write("document.write(\"    	<style type=\\\"text/css\\\">\");");
document.write("document.write(\"		.green {\");");
document.write("document.write(\"			background-color: green;\");");
document.write("document.write(\"		}\");");
document.write("document.write(\"		.blue {\");");
document.write("document.write(\"			background: rgb(48,36,255);\");");
document.write("document.write(\"			background: linear-gradient(90deg, rgba(48,36,255,1) 0%, rgba(6,6,114,1) 49%, rgba(5,45,255,1) 100%); \");");
document.write("document.write(\"		}\");");
document.write("document.write(\"		\");");
document.write("document.write(\"		a {\");");
document.write("document.write(\"        	color: #fff;\");");
document.write("document.write(\"		margin: 0;\");");
document.write("document.write(\"		text-decoration: none;\");");
document.write("document.write(\"			}\");");
document.write("document.write(\"\");");
document.write("document.write(\"	</style>\");");
document.write("document.write(\"    \");");
document.write("document.write(\"    \");");
document.write("document.write(\"    </head>\");");
document.write("document.write(\"    \");");
document.write("document.write(\"\");");
document.write("document.write(\"    <body bgcolor=\\\"FFFFFF\\\">\");");
document.write("document.write(\"        <center><img src=\\\"wtools.jpg\\\" align=\\\"bottom\\\"> </center>\");");
document.write("document.write(\"        <hr>\");");
document.write("document.write(\"        <a href=\\\"http://wtools.io\\\">Best Online Web Tools</a>is a link to another nifty site\");");
document.write("document.write(\"        <p class='blue'> This is a new paragraph!</p>\");");
document.write("document.write(\"        <h1>This is a Header</h1>\");");
document.write("document.write(\"        <h2>This is a Medium Header</h2>\");");
document.write("document.write(\"        Send me mail at <a href=\\\"mailto:support@example.com\\\">support@example.com</a>.\");");
document.write("document.write(\"        <p> This is a new paragraph!</p>\");");
document.write("document.write(\"        <p class='green'> This is a GREEN!</p>\");");
document.write("document.write(\"        <p> <b>This is a new paragraph!</b></p>\");");
document.write("document.write(\"        <br> <b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>\");");
document.write("document.write(\"        <hr>\");");
document.write("document.write(\"    </body>\");");
document.write("document.write(\"</html>\");");
document.write("");

