
document.write("<body>");
document.write("<!-- partial:index.partial.html -->");
document.write("<div class=\"container\">");
document.write("  <div class=\"row justify-content-center\">");
document.write("    <div class=\"col-lg-8 d-flex flex-column align-items-center\">");
document.write("      <img class=\"rounded-circle mt-4\" src=\"https://bit.ly/3x6oAph\" width=\"100\">");
document.write("      <p class=\"text-center text-white mb-0 mt-3\">@badiali</p>");
document.write("      <div class=\"card w-100 border-0 shadow mt-4\">");
document.write("        <ul class=\"list-group list-group-flush border-0\">");
document.write("          <li class=\"list-group-item border-0 text-center p-4\">");
document.write("            <p>Hola 👋 soy Luis <strong>Badiali</strong></p>");
document.write("            <p class=\"mb-0\">Me dedico al diseño y desarrollo frontend 👨‍💻 me apasiona el mar 🌊 la vela 🌬 ⛵️ y el arte 🎨</p>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("      <div class=\"card w-100 border-0 shadow mt-3\">");
document.write("        <div class=\"card-header border-0 text-center font-weight-bold\">");
document.write("          Artículos");
document.write("        </div>");
document.write("        <ul class=\"list-group list-group-flush border-0\">");
document.write("          <li class=\"list-group-item p-1\">");
document.write("            <a target=\"_blank\" rel=\"noopener noreferrer\" class=\"stretched-link d-flex align-items-center text-center\" href=\"https://dev.to/badiali/offcanvas-menu-usando-el-modal-de-bootstrap-emp\" title=\"Off-canvas menu usando el modal de Bootstrap | Luis Badiali\">");
document.write("              <img class=\"rounded\" src=\"https://badiali.es/assets/img/thumbs/off-canvas.png\" alt=\"DEV.to | Artículos Luis Badiali\">");
document.write("              <span class=\"flex-grow-1\">Off-canvas menu usando el modal de Bootstrap</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li class=\"list-group-item p-1\">");
document.write("            <a target=\"_blank\" rel=\"noopener noreferrer\" class=\"stretched-link d-flex align-items-center text-center\" href=\"https://dev.to/badiali/lista-desplegable-efecto-acordeon-con-bootstrap-3g19\" title=\"Lista desplegable efecto acordeón con Bootstrap | Luis Badiali\">");
document.write("              <img class=\"rounded\" src=\"https://badiali.es/assets/img/thumbs/acordeon.png\" alt=\"DEV.to | Artículos Luis Badiali\">");
document.write("              <span class=\"flex-grow-1\">Lista desplegable efecto acordeón con Bootstrap</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li class=\"list-group-item p-1\">");
document.write("            <a target=\"_blank\" rel=\"noopener noreferrer\" class=\"stretched-link d-flex align-items-center text-center\" href=\"https://dev.to/badiali/bootstrap-4-masonry-layout-js-25d2\" title=\"Listado con Bootstrap estilo Masonry sin JS | Luis Badiali\">");
document.write("              <img class=\"rounded\" src=\"https://badiali.es/assets/img/thumbs/masonry.png\" alt=\"DEV.to | Artículos Luis Badiali\">");
document.write("              <span class=\"flex-grow-1\">Listado con Bootstrap estilo Masonry sin JS</span>");
document.write("            </a>");
document.write("          </li>");

document.write("          <li class=\"list-group-item p-1\">");
document.write("            <a target=\"_blank\" rel=\"noopener noreferrer\" class=\"stretched-link d-flex align-items-center text-center\" href=\"https://dev.to/badiali/bootstrap-4-masonry-layout-js-25d2\" title=\"Listado con Bootstrap estilo Masonry sin JS | Luis Badiali\">");
document.write("              <img class=\"rounded\" src=\"https://badiali.es/assets/img/thumbs/masonry.png\" alt=\"DEV.to | Artículos Luis Badiali\">");
document.write("              <span class=\"flex-grow-1\">Listado con Bootstrap estilo Masonry sin JS</span>");
document.write("            </a>");
document.write("          </li>");

document.write("          <li class=\"list-group-item p-1\">");
document.write("            <a target=\"_blank\" rel=\"noopener noreferrer\" class=\"stretched-link d-flex align-items-center text-center\" href=\"https://dev.to/badiali/bootstrap-4-masonry-layout-js-25d2\" title=\"Listado con Bootstrap estilo Masonry sin JS | Luis Badiali\">");
document.write("              <img class=\"rounded\" src=\"https://badiali.es/assets/img/thumbs/masonry.png\" alt=\"DEV.to | Artículos Luis Badiali\">");
document.write("              <span class=\"flex-grow-1\">Listado con Bootstrap estilo Masonry sin JS</span>");
document.write("            </a>");
document.write("          </li>");

document.write("        </ul>");
document.write("      </div>");
document.write("      <div class=\"card w-100 border-0 shadow mt-3\">");
document.write("        <div class=\"card-header border-0 text-center font-weight-bold\">");
document.write("          Contacto");
document.write("        </div>");
document.write("        <ul class=\"list-group list-group-flush border-0\">");
document.write("          <li class=\"list-group-item border-0 p-1\">");
document.write("            <a class=\"stretched-link d-flex align-items-center text-center\" href=\"mailto:info@badiali.net\">");
document.write("              <span class=\"flex-grow-1\">Email</span>");
document.write("            </a>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("      <ul class=\"list-unstyled list-inline my-4\">");
document.write("        <li class=\"list-inline-item mx-2\">");
document.write("          <a class=\"text-white\" href=\"https://twitter.com/badiali/\" target=\"_blank\">");
document.write("            <i class=\"fab fa-twitter fa-2x\"></i>");
document.write("          </a>");
document.write("        </li>");
document.write("        <li class=\"list-inline-item mx-2\">");
document.write("          <a class=\"text-white\" href=\"https://instagram.com/dev.badiali/\" target=\"_blank\">");
document.write("            <i class=\"fab fa-instagram fa-2x\"></i>");
document.write("          </a>");
document.write("        </li>");
document.write("        <li class=\"list-inline-item mx-2\">");
document.write("          <a class=\"text-white\" href=\"https://github.com/badiali/\" target=\"_blank\">");
document.write("            <i class=\"fab fa-github fa-2x\"></i>");
document.write("          </a>");
document.write("        </li>");
document.write("        <li class=\"list-inline-item mx-2\">");
document.write("          <a class=\"text-white\" href=\"https://codepen.io/badiali/\" target=\"_blank\">");
document.write("            <i class=\"fab fa-codepen fa-2x\"></i>");
document.write("          </a>");
document.write("        </li>");
document.write("        <li class=\"list-inline-item mx-2\">");
document.write("          <a class=\"text-white\" href=\"https://es.linkedin.com/in/badiali/\" target=\"_blank\">");
document.write("            <i class=\"fab fa-linkedin fa-2x\"></i>");
document.write("          </a>");
document.write("        </li>");
document.write("      </ul>");
document.write("    </div>");
document.write("  </div>");
document.write("</div>");

